apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: item-inventory
  name: ventress8-item-inventory-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: ventress8
    server: https://kubernetes.default.svc
  project: ventress8
  source:
    path: lab3-4/apps/item-inventory/overlays
    repoURL: https://github.com/jbcodeforce/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

